# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         txt2html
version:      2.21
version_from: TextToHTML.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Basename:                0
    Getopt::ArgvFile:              0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
