--- #YAML:1.0
name: txt2html
version: 2.36
author:
  - Kathryn Andersen
abstract: convert plain text file to HTML
license: perl
requires:
  Data::Dumper: 0
  File::Basename: 0
  Getopt::ArgvFile: 0
  Getopt::Long: 0
  Pod::Usage: 0
  perl: 5.6.0
build_requires:
  Filter::Simple: 0.79
  Module::Build: 0.26
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.2607
