---
name: txt2html
version: 2.45
author:
  - Kathryn Andersen
abstract: convert plain text file to HTML.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Dumper: 0
  File::Basename: 0
  Getopt::ArgvFile: 0
  Getopt::Long: 0
  Pod::Usage: 0
  perl: 5.6.1
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  HTML::TextToHTML:
    file: lib/HTML/TextToHTML.pm
    version: 2.45
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
